[project]
name = "homebrew-tap"
version = "0.1.0"
description = ""
authors = [
    {name = "Shohei KAMON",email = "cameong@stir.network"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "toml (>=0.10.2,<0.11.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
