name: Update fireblocks-cli Formula on Dispatch

on:
  repository_dispatch:
    types: [fireblocks-cli-release]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Formula Update
        run: |
          pip install .
          python scripts/update_fireblocks-cli_formula.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/fireblocks-cli.rb
          git commit -m "fireblocks-cli: bump to ${{ github.event.client_payload.version }}" || echo "No changes to commit"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "fireblocks-cli: bump to ${{ github.event.client_payload.version }}"
          commit-message: "fireblocks-cli: bump to ${{ github.event.client_payload.version }}"
          branch: "bump/fireblocks-cli-${{ github.event.client_payload.version }}"
